name: Release Drafter

on:
  push:
    tags: 
      - v[0-9]+.[0-9]+.[0-9]*
  pull_request:
    # Only following types are handled by the action, but one can default to all as well
    types: [opened, reopened, synchronize]

jobs:
  update_release_draft:
    runs-on: ubuntu-latest
    steps:
      # Drafts your next Release notes as Pull Requests are merged into "master"
      - uses: release-drafter/release-drafter@v5
        name-template: 'v$RESOLVED_VERSION 🌈'
        tag-template: 'v$RESOLVED_VERSION'
        categories:
          - title: '🚀 Features'
            labels:
              - 'feature'
              - 'enhancement'
              - 'feat'
          - title: '🐛 Bug Fixes'
            labels:
              - 'fix'
              - 'bugfix'
              - 'bug'
          - title: '🧰 Maintenance'
            labels: 
              - 'chore'
              - 'docs'
        change-template: '- $TITLE @$AUTHOR (#$NUMBER)'
        change-title-escapes: '\<*_&' # You can add # and @ to disable mentions, and add ` to disable code blocks.
        version-resolver:
          major:
            labels:
              - 'major'
          minor:
            labels:
              - 'minor'
          patch:
            labels:
              - 'patch'
          default: patch
        template: |
          ## Changes

          $CHANGES
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}